manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kureyakey
      url-base: https://github.com/kureyakey
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3-branch
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: kureyakey
      revision: main
     - name: zmk-rgbled-widget
      remote: kureyakey
      revision: main
      path: zmk-rgbled-widget
      
    self:
    path: config
